### ISSUE TITLE
Error trying to run demo projects

### ISSUE THREAD

**Issue by ValorZard** [wgpu4k/wgpu4k#22]
```PS C:\Github\wgpu4k> .\gradlew examples:glfw:run
Type-safe project accessors is an incubating feature.
Project accessors enabled, but root project name not explicitly set for 'buildSrc'. Checking out the project in different folders will impact the generated code and implicitly the buildscript classpath, breaking caching.
Kotlin does not yet support 22 JDK target, falling back to Kotlin JVM_21 JVM target

> Task :buildSrc:compileKotlin
Kotlin does not yet support 22 JDK target, falling back to Kotlin JVM_21 JVM target
w: Inconsistent JVM-target compatibility detected for tasks 'compileJava' (22) and 'compileKotlin' (21).
This will become an error in Gradle 8.0.
Consider using JVM Toolchain: https://kotl.in/gradle/jvm/toolchain
Learn more about JVM-target validation: https://kotl.in/gradle/jvm/target-validation


> Task :buildSrc:jar
:jar: No valid plugin descriptors were found in META-INF/gradle-plugins

> Configure project :wgpu4k
JReleaser Gradle Plugin 1.13.1. Consider becoming a sponsor at https://opencollective.com/jreleaser
w: file:///C:/Github/wgpu4k/wgpu4k/build.gradle.kts:116:5: Experimental API in the Kotlin Gradle Plugin: No stability guarantees can be provided. The API could get removed in the future without replacement
w: New 'wasm' target is Work-in-Progress and is subject to change without notice. Please report encountered issues to https://kotl.in/issue

w: The following Kotlin/Native targets cannot be built on this machine and are disabled:
iosArm64, iosX64, macosArm64, macosX64
To hide this message, add 'kotlin.native.ignoreDisabledTargets=true' to the Gradle properties.

w: The Default Kotlin Hierarchy Template was not applied to 'project ':wgpu4k'':
Explicit .dependsOn() edges were configured for the following source sets:
[androidNativeArm64Main, androidNativeX64Main, iosArm64Main, iosX64Main, linuxArm64Main, linuxX64Main, macosArm64Main, macosX64Main, unmappedMain]

Consider removing dependsOn-calls or disabling the default template by adding
    'kotlin.mpp.applyDefaultHierarchyTemplate=false'
to your gradle.properties

Learn more about hierarchy templates: https://kotl.in/hierarchy-template


> Configure project :wgpu4k-toolkit
w: file:///C:/Github/wgpu4k/wgpu4k-toolkit/build.gradle.kts:24:5: This declaration needs opt-in. Its usage should be marked with '@org.jetbrains.kotlin.gradle.targets.js.dsl.ExperimentalWasmDsl' or '@OptIn(org.jetbrains.kotlin.gradle.targets.js.dsl.ExperimentalWasmDsl::class)'
w: file:///C:/Github/wgpu4k/wgpu4k-toolkit/build.gradle.kts:71:5: Experimental API in the Kotlin Gradle Plugin: No stability guarantees can be provided. The API could get removed in the future without replacement

> Configure project :examples:common
w: file:///C:/Github/wgpu4k/examples/common/build.gradle.kts:12:2: This declaration needs opt-in. Its usage should be marked with '@org.jetbrains.kotlin.gradle.targets.js.dsl.ExperimentalWasmDsl' or '@OptIn(org.jetbrains.kotlin.gradle.targets.js.dsl.ExperimentalWasmDsl::class)'
w: file:///C:/Github/wgpu4k/examples/common/build.gradle.kts:38:2: Experimental API in the Kotlin Gradle Plugin: No stability guarantees can be provided. The API could get removed in the future without replacement

> Configure project :examples:web-js
w: file:///C:/Github/wgpu4k/examples/web-js/build.gradle.kts:20:5: This declaration needs opt-in. Its usage should be marked with '@org.jetbrains.kotlin.gradle.targets.js.dsl.ExperimentalWasmDsl' or '@OptIn(org.jetbrains.kotlin.gradle.targets.js.dsl.ExperimentalWasmDsl::class)'
w: file:///C:/Github/wgpu4k/examples/web-js/build.gradle.kts:50:5: Experimental API in the Kotlin Gradle Plugin: No stability guarantees can be provided. The API could get removed in the future without replacement

> Task :wgpu4k:downloadFile-wgpu-linux-aarch64-release.zip
Download https://github.com/gfx-rs/wgpu-native/releases/download/v0.19.3.1/wgpu-linux-aarch64-release.zip

> Task :wgpu4k:downloadFile-wgpu-macos-x86_64-release.zip
Download https://github.com/gfx-rs/wgpu-native/releases/download/v0.19.3.1/wgpu-macos-x86_64-release.zip

> Task :wgpu4k:downloadFile-wgpu-macos-aarch64-release.zip
Download https://github.com/gfx-rs/wgpu-native/releases/download/v0.19.3.1/wgpu-macos-aarch64-release.zip

> Task :wgpu4k:downloadFile-wgpu-linux-x86_64-release.zip
Download https://github.com/gfx-rs/wgpu-native/releases/download/v0.19.3.1/wgpu-linux-x86_64-release.zip

> Task :wgpu4k:downloadFile-wgpu-windows-x86_64-release.zip
Download https://github.com/gfx-rs/wgpu-native/releases/download/v0.19.3.1/wgpu-windows-x86_64-release.zip

> Task :examples:glfw:run FAILED
will extract library to path C:\Program Files\Java\jdk-22\bin\WGPU0.dll
Exception in thread "main" java.nio.file.AccessDeniedException: C:\Program Files\Java\jdk-22\bin\WGPU0.dll
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:234)
        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:482)
        at java.base/java.nio.file.Files.newOutputStream(Files.java:227)
        at java.base/java.nio.file.Files.copy(Files.java:3145)
        at io.ygdrasil.wgpu.internal.jvm.LibraryLoaderKt.extractResourceToTemp(LibraryLoader.kt:95)
        at io.ygdrasil.wgpu.internal.jvm.LibraryLoaderKt.exportAndLoadLibrary(LibraryLoader.kt:14)
        at io.ygdrasil.wgpu.WGPU$Companion.loadLibrary(WGPU.kt:113)
        at io.ygdrasil.wgpu.examples.GlfwMainKt$main$1.invokeSuspend(GlfwMain.kt:18)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at io.ygdrasil.wgpu.examples.GlfwMainKt.main(GlfwMain.kt:17)
        at io.ygdrasil.wgpu.examples.GlfwMainKt.main(GlfwMain.kt)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':examples:glfw:run'.
> Process 'command 'C:\Program Files\Java\jdk-22\bin\java.exe'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.8/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 4m 20s
29 actionable tasks: 29 executed```

**Comment by ygdrasil-io** [comment]
Hello, thank you for your feedback.

This isn't the first time I've encountered issues with library extraction on Windows. I guess this part is a bit clunky. Give me some time to improve it, unless you have an idea about where to safely extract the library?

**Comment by ygdrasil-io** [comment]
Should be fix by https://github.com/wgpu4k/wgpu4k/pull/25. 
@ValorZard Could you retry from the main branch ?

**Comment by ValorZard** [comment]
it works!
