### ISSUE TITLE
Crash on JVM

### ISSUE THREAD

**Issue by Laxystem** [wgpu4k/wgpu4k#77]
```
WARNING: A restricted method in java.lang.foreign.AddressLayout has been called
WARNING: java.lang.foreign.AddressLayout::withTargetLayout has been called by io.ygdrasil.wgpu.internal.jvm.panama.wgpu_h in an unnamed module
WARNING: Use --enable-native-access=ALL-UNNAMED to avoid a warning for callers in this module
WARNING: Restricted methods will be blocked in a future release unless native access is enabled

Exception in thread "main" java.lang.UnsatisfiedLinkError: unresolved symbol: wgpuCreateInstance
	at io.ygdrasil.wgpu.internal.jvm.panama.wgpu_h.lambda$findOrThrow$0(wgpu_h.java:31)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at io.ygdrasil.wgpu.internal.jvm.panama.wgpu_h.findOrThrow(wgpu_h.java:31)
	at io.ygdrasil.wgpu.internal.jvm.panama.wgpu_h$wgpuCreateInstance.<clinit>(wgpu_h.java:4739)
	at io.ygdrasil.wgpu.internal.jvm.panama.wgpu_h.wgpuCreateInstance(wgpu_h.java:4780)
	at io.ygdrasil.wgpu.WGPU$Companion.createInstance$lambda$3(WGPU.kt:124)
	at io.ygdrasil.wgpu.internal.jvm.PanamaKt.confined(Panama.kt:10)
	at io.ygdrasil.wgpu.WGPU$Companion.createInstance(WGPU.kt:122)
	at io.ygdrasil.wgpu.WGPU$Companion.createInstance$default(WGPU.kt:122)
	at quest.laxla.spock.Wgpu_jvmKt.createWgpu(Wgpu.jvm.kt:23)
	at quest.laxla.spock.WgpuKt.Wgpu(Wgpu.kt:14)
	at quest.laxla.spock.MainKt.main(Main.kt:16)
	at quest.laxla.spock.MainKt$main$1.invokeSuspend(Main.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:263)
	at kotlinx.coroutines.DispatchedCoroutine.afterResume(Builders.common.kt:255)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:100)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)

```

**Comment by ygdrasil-io** [comment]
Did you call `WGPU.loadLibrary()` at startup? 
This will extract the library depending on your operating system and load it. Otherwise, Panama cannot find the library symbols, which is a JVM-specific requirement.

**Comment by Laxystem** [comment]
> Did you call `WGPU.loadLibrary()` at startup?

Nope! That explains, thanks!
